# Frontend Dockerfile - Nginx statikus fájlokhoz
FROM nginx:alpine

# Eltávolítjuk az alapértelmezett nginx konfigurációt
RUN rm /etc/nginx/conf.d/default.conf

# Másoljuk át az egyéni nginx konfigurációt
COPY nginx.conf /etc/nginx/conf.d/

# Másoljuk a frontend fájlokat az nginx web root-ba
COPY . /usr/share/nginx/html

# Expose port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]